#+TITLE: DOOM EMACS Config
#+AUTHOR: Lucien Fiorini
#+PROPERTY: header-args :tangle config.el

* Table of contents :toc:noexport:
- [[#introduction][Introduction]]
- [[#user-variables][User Variables]]
  - [[#name-and-email][Name and Email]]
- [[#ui][UI]]
  - [[#font][Font]]
  - [[#theme][Theme]]
  - [[#disable-mouse-support][Disable mouse support]]
- [[#editor][Editor]]
  - [[#relative-lines][Relative lines]]
- [[#org-mode][Org Mode]]
  - [[#set-the-org-directory][Set the org directory]]
  - [[#packages][Packages]]
- [[#programming][Programming]]
  - [[#c][C++]]
  - [[#godot][Godot]]
- [[#module-config][Module Config]]
  - [[#company][Company]]

* Introduction
#+BEGIN_QUOTE
This configuration is meant to be used with DOOM Emacs.
#+END_QUOTE
* User Variables
** Name and Email
#+BEGIN_SRC elisp
(setq user-full-name "Lucien Fiorini"
      user-mail-address "lucienfiorini@protonmail.com")
#+END_SRC
* UI
** Font
I don't set the size so that it can adapt automatically to the size of the screen, it will change in the future.
#+BEGIN_SRC elisp
(setq doom-font (font-spec :family "Source Code Pro" :size 16))
#+END_SRC
** Theme
Doom's themes are mostly really good !
#+BEGIN_SRC elisp
(setq doom-theme 'doom-gruvbox)
#+End_src
** TODO Disable mouse support
* Editor
** Relative lines
#+BEGIN_SRC elisp
(setq display-line-numbers-type 'relative)
#+END_SRC
* Org Mode
** Set the org directory
#+BEGIN_SRC elisp
(setq org-directory "~/misc/org/")
#+END_SRC
** Packages
*** ox-twbs
#+BEGIN_SRC elisp
(eval-after-load "org"
  '(require 'ox-twbs nil t))
#+END_SRC
* Programming
** C++
*** CPlusPlusMode
Enable .h file support
#+BEGIN_SRC elisp
(add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))
#+END_SRC
**** Style
I use K&R style indentatons.
#+BEGIN_SRC elisp
(defun my-c++-mode-hook ()
  (c-set-style "k&r")
  (setq c-basic-offset 4)
)

(add-hook 'c++-mode-hook 'my-c++-mode-hook)
#+END_SRC
** Godot
*** Packages
**** gdscript-mode
#+BEGIN_SRC elisp
(require 'gdscript-mode)
#+END_SRC

* Module Config
** Company
Reduce the idle delay.
#+BEGIN_SRC elisp
(setq company-idle-delay 0.2)
#+END_SRC
